import { AnimatePresence, motion } from 'framer-motion'
import { Award, Check, ChevronLeft, Edit3, Plus, Settings2, Sparkles, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { Certificate, ColorTheme, ScoreboardState } from '../types'
import { StatusPill } from './StatusPill'
import { ThemeToggle } from './ThemeToggle'

type Props = { state: ScoreboardState; status: 'loading' | 'ready' | 'error'; storageKind?: 'browser-sqlite' | 'tauri-sqlite'; theme: ColorTheme; onToggleTheme: () => void; onAdd: (title: string, winner?: string, citation?: string) => Promise<void>; onUpdate: (id: string, title: string, winner?: string, citation?: string) => Promise<void>; onDelete: (id: string) => Promise<void>; admin?: boolean }

function Header({ admin, ...props }: Pick<Props, 'admin' | 'status' | 'storageKind' | 'theme' | 'onToggleTheme'>) {
  return <header className="certificates-header"><div className="dashboard-title"><a href="#/"><ChevronLeft />Leaderboard</a><p>Awards night · {admin ? 'Certificate studio' : 'Honours gallery'}</p><h1>Certificates</h1></div><div className="header-actions"><StatusPill status={props.status} storageKind={props.storageKind} compact /><ThemeToggle theme={props.theme} onToggle={props.onToggleTheme} />{admin ? <a className="icon-button" href="#/certificates" title="Open awards gallery" aria-label="Open awards gallery"><Award /></a> : <a className="icon-button" href="#/certificates-admin" title="Manage certificates" aria-label="Manage certificates"><Settings2 /></a>}</div></header>
}

function CertificateCard({ certificate, onSelect }: { certificate: Certificate; onSelect: () => void }) {
  return <button className="certificate-card" onClick={onSelect}><span className="certificate-card-mark"><Award /></span><span className="certificate-card-title">{certificate.title}</span><span className="certificate-card-status">{certificate.winner ? 'Ready to reveal' : 'Winner to be announced'}</span><Sparkles className="certificate-card-spark" /></button>
}

function Reveal({ certificate, onClose }: { certificate: Certificate; onClose: () => void }) {
  const [revealed, setRevealed] = useState(false)
  return <div className="certificate-reveal-backdrop" role="dialog" aria-modal="true" aria-labelledby="certificate-reveal-title"><motion.section className={`certificate-reveal ${revealed ? 'revealed' : ''}`} initial={{ scale: .86, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><div className="reveal-ornament"><Award /></div><p className="eyebrow">Special award</p><h2 id="certificate-reveal-title">{certificate.title}</h2>{certificate.citation && <p className="certificate-citation">{certificate.citation}</p>}<AnimatePresence mode="wait">{revealed ? <motion.div key="winner" className="winner-reveal" initial={{ opacity: 0, y: 18, scale: .85 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ type: 'spring', stiffness: 130, damping: 12 }}><span>The certificate goes to</span><strong>{certificate.winner || 'Winner to be announced'}</strong><Check /></motion.div> : <motion.div key="hidden" className="winner-hidden" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><span>And the winner is…</span><div className="suspense-dots"><i /><i /><i /></div><button className="primary-action reveal-button" onClick={() => setRevealed(true)} disabled={!certificate.winner}>Reveal the winner <Sparkles /></button>{!certificate.winner && <small>Add a winner in the certificate studio first.</small>}</motion.div>}</AnimatePresence><button className="text-button" onClick={onClose}>Close certificate</button></motion.section></div>
}

function AdminForm({ editing, onSave, onCancel }: { editing?: Certificate; onSave: (title: string, winner: string, citation: string) => Promise<void>; onCancel: () => void }) {
  const [title, setTitle] = useState(editing?.title ?? ''); const [winner, setWinner] = useState(editing?.winner ?? ''); const [citation, setCitation] = useState(editing?.citation ?? '')
  return <form className="certificate-form" onSubmit={async (event) => { event.preventDefault(); await onSave(title, winner, citation); onCancel() }}><div className="form-pair"><label>Certificate title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Camp spirit award" required /></label><label>Winner<input value={winner} onChange={(event) => setWinner(event.target.value)} placeholder="Leave blank until awards night" /></label></div><label className="field-label">Citation <span>(optional)</span><textarea value={citation} onChange={(event) => setCitation(event.target.value)} placeholder="For showing joyful service…" rows={3} /></label><div className="form-actions"><button className="primary-action" type="submit">{editing ? <Check /> : <Plus />}{editing ? 'Save changes' : 'Add certificate'}</button><button className="text-button" type="button" onClick={onCancel}>Cancel</button></div></form>
}

export function CertificatesView({ state, admin = false, ...props }: Props) {
  const [selected, setSelected] = useState<Certificate>(); const [editing, setEditing] = useState<Certificate>(); const [showForm, setShowForm] = useState(false)
  return <main className="certificates-view"><Header admin={admin} {...props} /><section className="certificates-intro"><div><p className="eyebrow">Awards night</p><h2>Celebrate the people who made camp memorable.</h2><p>Select a certificate, then reveal the winner when the room is ready.</p></div>{admin && <button className="primary-action certificate-add" onClick={() => { setEditing(undefined); setShowForm(true) }}><Plus />Add certificate</button>}</section>{admin && showForm && <section className="control-card certificate-editor"><div className="control-card-heading"><div><p className="eyebrow">Certificate studio</p><h2>{editing ? 'Edit certificate' : 'New certificate'}</h2></div><Edit3 /></div><AdminForm editing={editing} onSave={(title, winner, citation) => editing ? props.onUpdate(editing.id, title, winner, citation) : props.onAdd(title, winner, citation)} onCancel={() => { setShowForm(false); setEditing(undefined) }} /></section>}<section className="certificate-grid">{state.certificates.length ? state.certificates.map((certificate) => <div className="certificate-admin-wrap" key={certificate.id}><CertificateCard certificate={certificate} onSelect={() => !admin && setSelected(certificate)} />{admin && <div className="certificate-admin-actions"><button onClick={() => { setEditing(certificate); setShowForm(true) }}><Edit3 />Edit</button><button onClick={() => void props.onDelete(certificate.id)}><Trash2 />Remove</button></div>}</div>) : <div className="certificate-empty"><Award /><h3>No certificates yet</h3><p>Add the first award in the certificate studio.</p></div>}</section>{selected && <Reveal certificate={selected} onClose={() => setSelected(undefined)} />}</main>
}
